name: oppgave_17
on: [push, workflow_dispatch]

jobs:
  job1:
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      - name: Run Blackjack script file
        run: "src/oppgave_10.ps1"
      - name: login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.OPPGAVE14 }}
          enable-AzPSSession: true 
      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v4.5
        with:
          modules-to-cache: Az.Storage, Az.Functions, Az.Websites, Az.Resources, Az.Accounts
      - name: Deploy Blackjack
        run: funcApp/deployWithBicep.ps1 -firstName "Kenneth" -resourceGroupName "Kenneth-workshop-isnbqb5navfm6"