name: oppgave_16
on: 
  push:
    paths:
      - '.github/workflows/oppgave_16.yml'
  workflow_dispatch:

jobs:
  job1:
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      - name: Run Blackjack script file
        run: "src/oppgave_10.ps1"
      - name: login (men hvorfor?)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.OPPGAVE14 }}
          enable-AzPSSession: true 